### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by eigenwillig** [mapbox/geojson-thumbnail#9]
I've verified my mail address, but it still doesn't work:

```
export MapboxAccessToken=pk.eyJ1Ijoic3Ryb21uZX[...]aHcyd3BobjEydTZ4Y3QifQ
geojson-thumbnail test.geojson test.png
```

```
/usr/lib/node_modules/@mapbox/geojson-thumbnail/bin/geojson-thumbnail.js:38
    if (err) throw err;
             ^

Error: Server returned HTTP 401
    at Request.<anonymous> (/usr/lib/node_modules/@mapbox/geojson-thumbnail/node_modules/@mapbox/tilejson/lib/tilejson.js:223:19)
    at Request._callback (/usr/lib/node_modules/@mapbox/geojson-thumbnail/node_modules/lodash/lodash.js:10050:25)
    at Request.requestRetryReply [as reply] (/usr/lib/node_modules/@mapbox/geojson-thumbnail/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/lib/node_modules/@mapbox/geojson-thumbnail/node_modules/requestretry/index.js:138:10)
    at Request.self.callback (/usr/lib/node_modules/@mapbox/geojson-thumbnail/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/@mapbox/geojson-thumbnail/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
```

**Comment by ingalls** [comment]
Did you use

```
export 
MapboxAccessToken
```

or

```
export MapboxAccessToken
```

**Comment by eigenwillig** [comment]
Of course in a single line. I'm using 100 % Linux since > 5 years.

**Comment by eigenwillig** [comment]
What do you mean with scope?

PS: You can already remove the "bug" label. I assume that this issue is a layer 8 problem.
Thanks for developing this tool!

**Comment by ingalls** [comment]
@eigenwillig If you go to the mapbox.com web interface and go to the token section of your account it should let you list "allowed actions" (scopes) of a particular token.

![screenshot from 2018-05-01 12-35-18](https://user-images.githubusercontent.com/1297009/39482212-23963f3e-4d3c-11e8-8194-8443a6e063ed.png)

**Comment by eigenwillig** [comment]
The final `.65iEY9SnvDxNPeCKo8Gkag` was missing!

**Comment by ingalls** [comment]
@eigenwillig Good stuff! Going to close, feel free to open a new ticket and cc @ingalls if you run into any more problems.
